# Generated by Django 4.1.3 on 2022-11-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addof',
            name='dob',
            field=models.DateField(default=False),
            preserve_default=False,
        ),
    ]
