# Generated by Django 4.1 on 2022-11-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_addof_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addof',
            name='dob',
        ),
    ]
